name: Sanity check (commit test)

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make data file
        run: |
          mkdir -p data
          echo "hello $(date -u +'%Y-%m-%dT%H:%M:%SZ')" > data/hello.txt
          ls -alh data
          cat data/hello.txt

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f data/hello.txt
          git status --porcelain
          if ! git diff --cached --quiet; then
            git commit -m "chore: sanity write test [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
